export const yieldContractABI = [
    "constructor(address,address,uint256,uint256,uint256)",
    "event OwnershipTransferred(address indexed,address indexed)",
    "event Paused(address)",
    "event Unpaused(address)",
    "function claim(address,uint256,uint256)",
    "function distributeDividend(uint256)",
    "function getBTCClaimAddress(address) view returns (uint256)",
    "function getClaimHistory(address) view returns (tuple(uint256,address,uint256,uint256)[])",
    "function getClaimable(address) view returns (uint256)",
    "function getClaimed(address) view returns (uint256)",
    "function getDistributionHistory() view returns (tuple(uint256,uint256,uint256,uint256,uint256,uint256,uint256)[])",
    "function getHotWalletAddress() view returns (string)",
    "function getOperatorClaimHistroy() view returns (tuple(uint256,address,uint256,uint256)[])",
    "function getOperatorFeeBalance() view returns (uint256)",
    "function getTotalClaimed() view returns (uint256)",
    "function getUnclaimed() view returns (uint256)",
    "function owner() view returns (address)",
    "function pause()",
    "function paused() view returns (bool)",
    "function recordOperatorClaim(uint256,uint256)",
    "function renounceOwnership()",
    "function setBtcClaimAddress(string)",
    "function setCommissionPercent(uint256)",
    "function setElectricityFee(uint256)",
    "function setHostingFee(uint256)",
    "function setHotWalletAddress(string)",
    "function setLokaBTC(address)",
    "function transferOwnership(address)",
    "function unpause()",
];
